using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Judge : MonoBehaviour
{
    // ï¿½Ïï¿½ï¿½ÌéŒ¾
    [SerializeField] private GameObject[] MessageObj; // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½É”ï¿½ï¿½ï¿½ï¿½`ï¿½ï¿½ï¿½ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì”zï¿½ï¿½
    [SerializeField] NotesManager notesManager; // NotesManagerï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
    [SerializeField] TextMeshProUGUI comboText; // ï¿½Rï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½TextMeshProUGUIï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    [SerializeField] TextMeshProUGUI scoreText; // ï¿½Xï¿½Rï¿½Aï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½TextMeshProUGUIï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    [SerializeField] GameObject finish; // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½É•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    private new AudioSource audio; // ï¿½Iï¿½[ï¿½fï¿½Bï¿½Iï¿½\ï¿½[ï¿½Xï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½g
    [SerializeField] AudioClip hitSound; // ï¿½mï¿½[ï¿½cï¿½ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½Ê‰ï¿½
    float endTime = 0; // ï¿½Qï¿½[ï¿½ï¿½ï¿½ÌIï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

    private void Start()
    {
        // ï¿½Iï¿½[ï¿½fï¿½Bï¿½Iï¿½\ï¿½[ï¿½Xï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½æ“¾
        audio = GetComponent<AudioSource>();
        // ï¿½ÅŒï¿½Ìƒmï¿½[ï¿½cï¿½Ìï¿½ï¿½Ô‚ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½Aï¿½Qï¿½[ï¿½ï¿½ï¿½ÌIï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½İ’ï¿½
        endTime = notesManager.NotesTime[notesManager.NotesTime.Count - 1];
    }

    void Update()
    {
        // ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡
        if (GManagerReon.instance.Start)
        {
            // ï¿½Lï¿½[ï¿½ï¿½ï¿½Í‚É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½[ï¿½cï¿½Ì”ï¿½ï¿½ï¿½
            if (Input.GetKeyDown(KeyCode.D)) // "D"ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½
            {
                if (notesManager.LaneNum[0] == 0) // ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ì”Ôï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½é‚©ï¿½mï¿½F
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[0] + GManagerReon.instance.StartTime)), 0);
                }
                else if (notesManager.LaneNum[1] == 0)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[1] + GManagerReon.instance.StartTime)), 1);
                }
            }

            if (Input.GetKeyDown(KeyCode.F)) // "F"ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½
            {
                if (notesManager.LaneNum[0] == 1)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[0] + GManagerReon.instance.StartTime)), 0);
                }
                else if (notesManager.LaneNum[1] == 1)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[1] + GManagerReon.instance.StartTime)), 1);
                }
            }

            if (Input.GetKeyDown(KeyCode.J)) // "J"ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½
            {
                if (notesManager.LaneNum[0] == 2)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[0] + GManagerReon.instance.StartTime)), 0);
                }
                else if (notesManager.LaneNum[1] == 2)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[1] + GManagerReon.instance.StartTime)), 1);
                }
            }

            if (Input.GetKeyDown(KeyCode.K)) // "K"ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½
            {
                if (notesManager.LaneNum[0] == 3)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[0] + GManagerReon.instance.StartTime)), 0);
                }
                else if (notesManager.LaneNum[1] == 3)
                {
                    Judgement(GetABS(Time.time - (notesManager.NotesTime[1] + GManagerReon.instance.StartTime)), 1);
                }
            }

            // ï¿½ÅŒï¿½Ìƒmï¿½[ï¿½cï¿½ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
            if (Time.time > endTime + GManagerReon.instance.StartTime)
            {
                finish.SetActive(true); // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½\ï¿½ï¿½
                Invoke("ResuleScene", 3f); // 3ï¿½bï¿½ï¿½ÉŒï¿½ï¿½Ê‰ï¿½Ê‚É‘Jï¿½ï¿½
                return;
            }

            // ï¿½mï¿½[ï¿½cï¿½ï¿½@ï¿½ï¿½ï¿½×‚ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½0.2ï¿½bï¿½oï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡
            if (Time.time > notesManager.NotesTime[0] + 0.2f + GManagerReon.instance.StartTime)
            {
                message(3); // ï¿½~ï¿½Xï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½\ï¿½ï¿½
                deleteData(0); // ï¿½mï¿½[ï¿½cï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
                Debug.Log("Miss"); // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½Oï¿½ï¿½"Miss"ï¿½ï¿½\ï¿½ï¿½
                GManagerReon.instance.miss++; // ï¿½~ï¿½Xï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ğ‘‰ï¿½
                GManagerReon.instance.combo = 0; // ï¿½Rï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
            }
        }
    }

    // ï¿½mï¿½[ï¿½cï¿½Ì”ï¿½ï¿½èˆï¿½ï¿½
    void Judgement(float timeLag, int numOffset)
    {
        audio.PlayOneShot(hitSound); // ï¿½ï¿½ï¿½Ê‰ï¿½ï¿½ï¿½ï¿½Äï¿½
        if (timeLag <= 0.05) // ï¿½ï¿½ï¿½èï¿½Ô‚ï¿½0.05ï¿½bï¿½È‰ï¿½ï¿½Ìê‡
        {
            Debug.Log("Perfect"); // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½Oï¿½ï¿½"Perfect"ï¿½ï¿½\ï¿½ï¿½
            message(0); // ï¿½pï¿½[ï¿½tï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½\ï¿½ï¿½
            GManagerReon.instance.ratioScore += 5; // ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Z
            GManagerReon.instance.perfect++; // ï¿½pï¿½[ï¿½tï¿½Fï¿½Nï¿½gï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ğ‘‰ï¿½
            GManagerReon.instance.combo++; // ï¿½Rï¿½ï¿½ï¿½{ï¿½ğ‘‰ï¿½
            deleteData(numOffset); // ï¿½mï¿½[ï¿½cï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        }
        else if (timeLag <= 0.08) // ï¿½ï¿½ï¿½èï¿½Ô‚ï¿½0.08ï¿½bï¿½È‰ï¿½ï¿½Ìê‡
        {
            Debug.Log("Great"); // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½Oï¿½ï¿½"Great"ï¿½ï¿½\ï¿½ï¿½
            message(1); // ï¿½Oï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½\ï¿½ï¿½
            GManagerReon.instance.ratioScore += 3; // ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Z
            GManagerReon.instance.great++; // ï¿½Oï¿½ï¿½ï¿½[ï¿½gï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ğ‘‰ï¿½
            GManagerReon.instance.combo++; // ï¿½Rï¿½ï¿½ï¿½{ï¿½ğ‘‰ï¿½
            deleteData(numOffset); // ï¿½mï¿½[ï¿½cï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        }
        else if (timeLag <= 0.10) // ï¿½ï¿½ï¿½èï¿½Ô‚ï¿½0.10ï¿½bï¿½È‰ï¿½ï¿½Ìê‡
        {
            Debug.Log("Bad"); // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½Oï¿½ï¿½"Bad"ï¿½ï¿½\ï¿½ï¿½
            message(2); // ï¿½oï¿½bï¿½hï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½\ï¿½ï¿½
            GManagerReon.instance.ratioScore += 1; // ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Z
            GManagerReon.instance.bad++; // ï¿½oï¿½bï¿½hï¿½Jï¿½Eï¿½ï¿½ï¿½gï¿½ğ‘‰ï¿½
            GManagerReon.instance.combo = 0; // ï¿½Rï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
            deleteData(numOffset); // ï¿½mï¿½[ï¿½cï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        }
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½Î’lï¿½ï¿½Ô‚ï¿½ï¿½Öï¿½
    float GetABS(float num)
    {
        if (num >= 0)
        {
            return num;
        }
        else
        {
            return -num;
        }
    }

    // ï¿½ï¿½ï¿½Å‚É’@ï¿½ï¿½ï¿½ï¿½ï¿½mï¿½[ï¿½cï¿½ï¿½ï¿½íœï¿½ï¿½ï¿½ï¿½Öï¿½
    void deleteData(int numOffset)
    {
        notesManager.NotesTime.RemoveAt(numOffset); // ï¿½mï¿½[ï¿½cï¿½ï¿½ï¿½Ôƒfï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        notesManager.LaneNum.RemoveAt(numOffset); // ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ôï¿½ï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        notesManager.NoteType.RemoveAt(numOffset); // ï¿½mï¿½[ï¿½cï¿½^ï¿½Cï¿½vï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½íœ
        GManagerReon.instance.score = (int)Math.Round(1000000 * Math.Floor(
            GManagerReon.instance.ratioScore / GManagerReon.instance.maxScore * 1000000) / 1000000); // ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ÄXï¿½V
        comboText.text = GManagerReon.instance.combo.ToString(); // ï¿½Rï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½V
        scoreText.text = GManagerReon.instance.score.ToString(); // ï¿½Xï¿½Rï¿½Aï¿½ï¿½ï¿½Xï¿½V
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½
    void message(int judge)
    {
        Instantiate(MessageObj[judge],
            new Vector3(notesManager.LaneNum[0] - 1.5f, 0.76f, 0.15f),
            Quaternion.Euler(45, 0, 0));
    }

    // ï¿½ï¿½ï¿½Ê‰ï¿½Ê‚É‘Jï¿½Ú‚ï¿½ï¿½ï¿½Öï¿½
    private void ResuleScene()
    {
        SceneManager.LoadScene("ResultScene");
    }
}